import CryptoKit
import Darwin
import Foundation
import PulseCore

/// File protocol (v1) between an agent's hook on this Mac and Pulse on the
/// same Mac. The hook raises a permission request and holds; Pulse shows the
/// complete request and, if the user decides, writes a signed verdict the
/// hook claims. Nothing leaves the machine: 22.0 removed the per-host remote
/// trees (`requests.d/`, `verdicts.d/`, `secrets/`) along with the shared
/// `respond-secret.key`. Layout under
/// `~/Library/Application Support/Pulse/respond.d/`:
///
///   requests/<request_id>.json            — written by the hook (the
///                                            verbatim hook stdin, base64)
///   verdicts/<request_id>.json            — written by Pulse; claimed by the
///                                            hook by rename → .used
///   ../respond-local.key                  — generated by Pulse when local
///                                            answering is switched on; its
///                                            existence *is* the opt-in
///
/// Byte-for-byte the same protocol as `src/pulse_hook.py`'s Respond section.
///
/// Disciplines, in the same spirit as the AGENTS invariants:
///
/// - **No key, no hold, no verdict on disk — fail closed.** An install that
///   never switched local answering on sees no change in agent behaviour,
///   and every failure falls open to the vendor's own prompt.
/// - **A verdict is signed, not trusted.** The HMAC over the canonical string
///   binds request id + content digest + agent + host; only the local key
///   can mint it, and it never leaves this Mac.
/// - **Reads are bounded** in files and bytes per file.
/// - **`request_id` is untrusted text that becomes a file name.** It is
///   sanitized to `[A-Za-z0-9._-]`, capped, and never allowed to be a
///   pure-dot component, so a hostile id cannot climb out of the spool.
package enum RespondSpool {
    /// Tests redirect the spool without touching the user's real
    /// Application Support tree — same seam as `AttentionIO.pathOverride`.
    nonisolated(unsafe) package static var rootOverride: URL?

    package static var root: URL {
        if let rootOverride { return rootOverride }
        if let home = ProcessInfo.processInfo.environment["PULSE_HOME"]?
            .trimmingCharacters(in: .whitespacesAndNewlines),
           !home.isEmpty {
            return URL(fileURLWithPath: home, isDirectory: true)
                .appendingPathComponent("respond.d", isDirectory: true)
        }
        return FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent(
                "Library/Application Support/Pulse/respond.d", isDirectory: true
            )
    }

    package static var requestsDirectory: URL {
        root.appendingPathComponent("requests", isDirectory: true)
    }
    package static var verdictsDirectory: URL {
        root.appendingPathComponent("verdicts", isDirectory: true)
    }

    /// Same bounds philosophy as `AttentionIO`: a misbehaving writer must
    /// not be able to make Pulse read without limit.
    package static let maxFiles = 32
    package static let maxBytesPerFile = 256 * 1024
    /// A key is dozens of bytes. A "key" the size of a document is a
    /// mistake, and signing with a mistake is worse than refusing — fail
    /// closed.
    package static let maxSecretBytes = 4 * 1024
    /// How long an expired request may linger before `cleanup` removes it,
    /// so a verdict's fate can still be read for a while after the hold.
    package static let cleanupGraceMs: Int64 = 60 * 60 * 1000

    /// One permission request, ready for the decision store.
    package struct InboundRequest: Equatable {
        package var request: PermissionRequest
        package var toolName: String
        package var expiresAtMs: Int64

        package init(request: PermissionRequest, toolName: String, expiresAtMs: Int64) {
            self.request = request
            self.toolName = toolName
            self.expiresAtMs = expiresAtMs
        }
    }

    // MARK: - Reading requests

    /// The requests this Mac's agents are holding for, bounded: at most
    /// `maxFiles` files touched, each at most `maxBytesPerFile`; anything
    /// unparseable or expired is skipped.
    ///
    /// `fullRequest` is the UTF-8 text decoded from `payload_b64`. The digest
    /// is then recomputed over that text and compared with the file's own
    /// `digest` field: any mismatch — a payload that was not valid UTF-8, or
    /// plain tampering — marks the request `truncated`, and a truncated
    /// request can never be Allowed (`PermissionRequest.canOfferAllow`). An
    /// agent string that matches no `AgentID` skips the file entirely:
    /// guessing who is asking is exactly how a verdict ends up answering the
    /// wrong thing. A file claiming a host that is not this one is skipped
    /// rather than adopted.
    package static func readLocalRequests(nowMs: Int64, host: String) -> [InboundRequest] {
        readLocalRequests(nowMs: nowMs, host: host, in: requestsDirectory)
    }

    /// Hard ceiling on request files opened in one read, expired or not —
    /// expired files do not spend `maxFiles`, but reading stays bounded.
    package static let maxFilesScanned = 4 * maxFiles

    /// The same read over an explicit directory (tests pass a temp one, so
    /// they never share `rootOverride`).
    ///
    /// Newest first by modification date, so a live hold is read before the
    /// leftovers `cleanup` has not reached yet. The `maxFiles` budget counts
    /// files *touched*, not files parsed — otherwise a directory of garbage
    /// would defeat the bound while every file "doesn't count" — except an
    /// expired request: it is a well-formed file whose hold is over, and a
    /// spool full of those must not hide a live one. `maxFilesScanned`
    /// still caps every file opened.
    package static func readLocalRequests(
        nowMs: Int64, host: String, in directory: URL
    ) -> [InboundRequest] {
        guard !host.isEmpty else { return [] }
        let fm = FileManager.default
        guard let names = try? fm.contentsOfDirectory(atPath: directory.path)
        else { return [] }
        let candidates = names
            .filter { $0.hasSuffix(".json") }
            .map { name -> (url: URL, name: String, modifiedMs: Int64) in
                let url = directory.appendingPathComponent(name)
                return (url, name, modificationMs(of: url))
            }
            .sorted {
                // Newest first; the name breaks ties so the order is stable.
                $0.modifiedMs != $1.modifiedMs ? $0.modifiedMs > $1.modifiedMs : $0.name < $1.name
            }
        var found: [InboundRequest] = []
        var touched = 0
        var scanned = 0
        for candidate in candidates {
            if touched >= maxFiles || scanned >= maxFilesScanned { break }
            scanned += 1
            switch parseRequestFile(at: candidate.url, host: host, nowMs: nowMs) {
            case .request(let inbound):
                touched += 1
                found.append(inbound)
            case .expired:
                continue
            case .skipped:
                touched += 1
            }
        }
        return found
    }

    private enum ParsedRequest {
        case request(InboundRequest)
        /// Well-formed, for this host, but its hold is over.
        case expired
        /// Unreadable, another host's, an unknown agent, or a bad payload.
        case skipped
    }

    private static func parseRequestFile(
        at url: URL, host: String, nowMs: Int64
    ) -> ParsedRequest {
        guard let data = boundedRead(url, limit: maxBytesPerFile),
              let file = try? JSONDecoder().decode(RequestFile.self, from: data),
              file.v == 1
        else { return .skipped }
        // The verdict is bound to the host the request names; a request that
        // names another machine was not raised here.
        guard file.host == host else { return .skipped }
        // Unknown agent → skip, never guess (see the method doc).
        guard let agent = AgentID(rawValue: file.agent) else { return .skipped }
        guard nowMs < file.expiresAtMs else { return .expired }
        guard let payload = Data(base64Encoded: file.payloadB64) else { return .skipped }
        let fullRequest = String(decoding: payload, as: UTF8.self)
        // Recompute over the decoded *text*, not the raw bytes: the verdict's
        // digest binding (`PermissionRequest.digest`) is over the text, so
        // this comparison also catches a payload whose bytes were not valid
        // UTF-8 and changed in decoding.
        let digestMatches = RespondDigest.of(fullRequest) == file.digest.lowercased()
        let request = PermissionRequest(
            id: file.requestID,
            agent: agent,
            host: file.host,
            session: file.session,
            fullRequest: fullRequest,
            truncated: file.truncated || !digestMatches,
            // When the bytes landed on disk — the file's own stamp, not a
            // field its writer chose.
            receivedAtMs: modificationMs(of: url)
        )
        return .request(InboundRequest(
            request: request, toolName: file.toolName, expiresAtMs: file.expiresAtMs
        ))
    }

    // MARK: - The key

    /// Raw key bytes with trailing newlines trimmed — a key written by hand
    /// with `echo` or an editor gains a final `\n`, and the hook trims the
    /// same way (`pulse_hook.py load_respond_key`), so both ends agree.
    private static func keyBytes(at url: URL) -> Data? {
        guard var data = boundedRead(url, limit: maxSecretBytes) else { return nil }
        while let last = data.last, last == 0x0A || last == 0x0D {
            data.removeLast()
        }
        return data.isEmpty ? nil : data
    }

    // MARK: - Writing verdicts

    /// Sign a verdict with the local key and put it where the waiting hook
    /// is polling. No key, empty host, or an IO failure → false: nothing is
    /// written and the hook falls open to the vendor's prompt at its
    /// deadline. 0600, temp file then atomic rename.
    ///
    /// The HMAC covers the canonical string
    /// `"v1\n" + request_id + "\n" + digest + "\n" + agent + "\n" + host +
    ///  "\n" + ("allow"|"deny") + "\n" + decided_at_ms + "\n" + expires_at_ms`
    /// so the hook can verify both that the verdict is untampered and that it
    /// was minted by someone holding the local key, which never leaves this
    /// Mac. An attacker who can read it already runs as this user and could
    /// simply start the agent.
    @discardableResult
    package static func writeVerdict(_ verdict: RespondVerdict) -> Bool {
        guard !verdict.host.isEmpty else { return false }
        guard let key = localKey() else { return false }
        guard let data = signedVerdictData(verdict, key: key) else { return false }
        // A verdict can cause an agent to act; the whole tree stays user-only.
        try? FileManager.default.createDirectory(
            at: verdictsDirectory, withIntermediateDirectories: true,
            attributes: [.posixPermissions: 0o700]
        )
        let destination = verdictsDirectory
            .appendingPathComponent(sanitizeComponent(verdict.requestID) + ".json")
        return atomicWrite0600(data, to: destination)
    }

    private static func signedVerdictData(_ verdict: RespondVerdict, key: Data) -> Data? {
        let message = canonicalMessage(
            requestID: verdict.requestID, digest: verdict.digest,
            agent: verdict.agent, host: verdict.host, allow: verdict.allow,
            decidedAtMs: verdict.decidedAtMs, expiresAtMs: verdict.expiresAtMs
        )
        let mac = HMAC<SHA256>.authenticationCode(
            for: message, using: SymmetricKey(data: key)
        )
        let body = VerdictFile(
            v: 1,
            requestID: verdict.requestID,
            digest: verdict.digest,
            agent: verdict.agent,
            host: verdict.host,
            allow: verdict.allow,
            decidedAtMs: verdict.decidedAtMs,
            expiresAtMs: verdict.expiresAtMs,
            hmac: mac.map { String(format: "%02x", $0) }.joined()
        )
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.sortedKeys]
        return try? encoder.encode(body)
    }

    // MARK: - Expiry

    private static func expiryMs(of url: URL) -> Int64? {
        guard let data = boundedRead(url, limit: maxBytesPerFile),
              let object = (try? JSONSerialization.jsonObject(with: data)) as? [String: Any],
              let number = object["expires_at_ms"] as? NSNumber
        else { return nil }
        return number.int64Value
    }

    // MARK: - The hold's side of the protocol
    //
    // Every constant and semantic below is frozen with `src/pulse_hook.py` —
    // change both or neither.

    /// Clock tolerance on a verdict's timestamps, ±5 min, in the direction
    /// that keeps a genuinely fresh verdict usable: unexpired while
    /// `now < expires + skew`, plausibly decided while `decided - skew <= now`.
    /// Both ends read the same clock now, so this only matters when the clock
    /// is adjusted mid-hold; the exactly-once `.used` rename means even a
    /// late verdict can only answer this one held request.
    /// (= RESPOND_CLOCK_SKEW_MS)
    package static let respondClockSkewMs: Int64 = 300_000
    /// `.used` remnants older than an hour are removed. (= RESPOND_USED_TTL_MS)
    package static let usedVerdictTtlMs: Int64 = 3_600_000
    /// Cap per spool directory, oldest deleted first. (= RESPOND_DIR_MAX_FILES)
    package static let maxFilesPerDirectory = 64

    /// `<pulse_dir>/respond-local.key` — beside `respond.d`, generated here
    /// and never carried anywhere.
    package static var localSecretURL: URL {
        root.deletingLastPathComponent().appendingPathComponent("respond-local.key")
    }

    /// Answering this Mac's own agents is opt-in, and the key file's existence
    /// *is* the switch — and the kill switch: no key, no hold, so an install
    /// that never turns this on sees no change in agent behaviour at all.
    package static func localHasSecret() -> Bool {
        localKey() != nil
    }

    private static func localKey() -> Data? {
        keyBytes(at: localSecretURL)
    }

    /// Turn local answering on or off by creating or removing the key.
    ///
    /// Written as hex text on purpose: `keyBytes` trims trailing newline
    /// bytes, and raw random bytes ending in 0x0A would be silently trimmed
    /// into a different key than the one written.
    @discardableResult
    package static func setLocalAnsweringEnabled(_ enabled: Bool) -> Bool {
        guard enabled else {
            try? FileManager.default.removeItem(at: localSecretURL)
            return !localHasSecret()
        }
        if localHasSecret() { return true }
        let hex = (0..<32)
            .map { _ in String(format: "%02x", UInt8.random(in: UInt8.min...UInt8.max)) }
            .joined()
        return PrivateFile.write(Data(hex.utf8), to: localSecretURL)
    }

    /// Write this machine's own permission request for Pulse to show,
    /// mirroring `pulse_hook.py respond_decision_json`'s record: the payload
    /// is the **verbatim** hook stdin (base64), the digest is over those
    /// exact bytes, and `truncated` is false because nothing was cut.
    /// Housekeeping (`cleanup`) runs alongside every write, exactly like the
    /// Python side.
    @discardableResult
    package static func writeRequest(
        requestID: String,
        agent: String,
        host: String,
        session: String,
        cwd: String,
        toolName: String,
        payload: Data,
        nowMs: Int64,
        expiresAtMs: Int64
    ) -> Bool {
        // No id → a verdict could not be bound; no bytes → nothing the user
        // could actually review. Either way there is nothing to hold for.
        guard !requestID.isEmpty, !payload.isEmpty else { return false }
        let fm = FileManager.default
        for directory in [root, requestsDirectory, verdictsDirectory] {
            try? fm.createDirectory(
                at: directory, withIntermediateDirectories: true,
                attributes: [.posixPermissions: 0o700]
            )
        }
        let record = RequestFile(
            v: 1,
            requestID: requestID,
            agent: agent,
            host: host,
            session: session,
            cwd: cwd,
            toolName: toolName,
            raisedAtMs: nowMs,
            expiresAtMs: expiresAtMs,
            payloadB64: payload.base64EncodedString(),
            digest: RespondDigest.of(payload),
            truncated: false
        )
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.sortedKeys]
        guard let data = try? encoder.encode(record) else { return false }
        let destination = requestsDirectory
            .appendingPathComponent(sanitizeComponent(requestID) + ".json")
        let written = atomicWrite0600(data, to: destination)
        cleanup(nowMs: nowMs)
        return written
    }

    /// One poll of the verdict spool — the hold loop's sleep lives in the
    /// caller so tests can run on a fake clock.
    ///
    /// Exactly-once, frozen with `pulse_hook.py hold_for_verdict`: the file
    /// is claimed by renaming it to `.used` **before** it is read, and only a
    /// successful rename may be read and acted on. A rename that fails (file
    /// absent, or another process claimed it) is no verdict. A claimed
    /// verdict that fails verification stays consumed — the caller keeps
    /// waiting for a fresh file rather than re-reading a bad one.
    ///
    /// Returns the verdict's `allow`, or nil for "keep waiting". An allow for
    /// a truncated request is refused here as well: deny stays available, but
    /// approving something not fully captured must be impossible end to end.
    package static func claimVerdict(
        requestID: String,
        digest: String,
        agent: String,
        host: String,
        truncated: Bool = false,
        nowMs: Int64
    ) -> Bool? {
        let name = sanitizeComponent(requestID) + ".json"
        let verdictURL = verdictsDirectory.appendingPathComponent(name)
        let usedURL = verdictsDirectory.appendingPathComponent(name + ".used")
        // The rename IS the claim. rename(2) atomically replaces an existing
        // `.used` remnant, so a fresh verdict can still land after a bad one.
        guard rename(verdictURL.path, usedURL.path) == 0 else { return nil }
        // From here on, every failure leaves the file consumed on purpose.
        // Only the local key can have minted a verdict this hook will act on.
        guard let key = localKey() else { return nil }
        guard let data = boundedRead(usedURL, limit: maxBytesPerFile),
              let verdict = try? JSONDecoder().decode(VerdictFile.self, from: data),
              verdict.v == 1,
              verdict.requestID == requestID,
              verdict.digest == digest,
              verdict.agent == agent,
              verdict.host == host
        else { return nil }
        // Clock-skew windows — see respondClockSkewMs for the direction.
        guard nowMs < verdict.expiresAtMs + respondClockSkewMs else { return nil }
        guard verdict.decidedAtMs - respondClockSkewMs <= nowMs else { return nil }
        // Constant-time MAC check: decode the claimed hex and let CryptoKit
        // compare, rather than comparing hex strings ourselves. Undecodable
        // hex is a refusal, not an error.
        guard let mac = hexBytes(verdict.hmac) else { return nil }
        let message = canonicalMessage(
            requestID: verdict.requestID, digest: verdict.digest,
            agent: verdict.agent, host: verdict.host, allow: verdict.allow,
            decidedAtMs: verdict.decidedAtMs, expiresAtMs: verdict.expiresAtMs
        )
        guard HMAC<SHA256>.isValidAuthenticationCode(
            mac, authenticating: message, using: SymmetricKey(data: key)
        ) else { return nil }
        if verdict.allow && truncated { return nil }
        return verdict.allow
    }

    /// What became of a verdict this Mac wrote for one of its own agents.
    ///
    /// Not a guess: `claimVerdict` collects a verdict by **renaming** it to
    /// `<id>.json.used` before reading it, so the claim leaves a mark on disk.
    /// Reading that mark is the difference between Pulse reporting what it
    /// did and Pulse reporting what happened.
    package enum VerdictFate: Equatable {
        /// Written, still sitting there, still in time.
        case waiting
        /// The hook took it. This is the receipt.
        case taken
        /// Its deadline passed with the file untouched — the agent fell back
        /// to the vendor's own prompt, which is the designed failure.
        case expired
        /// Nothing on disk under that id: never written here, or swept.
        case unknown
    }

    package static func localVerdictFate(requestID: String, nowMs: Int64) -> VerdictFate {
        let fm = FileManager.default
        let name = sanitizeComponent(requestID) + ".json"
        let pending = verdictsDirectory.appendingPathComponent(name)
        // `.used` first: a fresh verdict can land while an older `.used`
        // remnant is still around, and "taken" is the newer fact only when
        // nothing is waiting.
        if !fm.fileExists(atPath: pending.path) {
            let used = verdictsDirectory.appendingPathComponent(name + ".used")
            return fm.fileExists(atPath: used.path) ? .taken : .unknown
        }
        guard let expiry = expiryMs(of: pending) else { return .waiting }
        return nowMs >= expiry ? .expired : .waiting
    }

    /// Housekeeping, frozen with `pulse_hook.py cleanup_respond_dirs`:
    /// requests go one hour past their own expiry (mtime fallback for the
    /// unreadable), `.used` remnants go after an hour, and each directory is
    /// capped at 64 files oldest-first. Deliberately not bounded like the
    /// read path: deleting is how the read bounds recover.
    package static func cleanup(nowMs: Int64) {
        let fm = FileManager.default
        if let names = try? fm.contentsOfDirectory(atPath: requestsDirectory.path) {
            for name in names where name.hasSuffix(".json") {
                let url = requestsDirectory.appendingPathComponent(name)
                if let expiry = expiryMs(of: url) {
                    if nowMs > expiry + cleanupGraceMs { try? fm.removeItem(at: url) }
                } else if nowMs - modificationMs(of: url) > cleanupGraceMs {
                    try? fm.removeItem(at: url)
                }
            }
        }
        if let names = try? fm.contentsOfDirectory(atPath: verdictsDirectory.path) {
            for name in names where name.hasSuffix(".used") {
                let url = verdictsDirectory.appendingPathComponent(name)
                if nowMs - modificationMs(of: url) > usedVerdictTtlMs {
                    try? fm.removeItem(at: url)
                }
            }
        }
        pruneOldest(requestsDirectory, keep: maxFilesPerDirectory)
        pruneOldest(verdictsDirectory, keep: maxFilesPerDirectory)
    }

    private static func pruneOldest(_ directory: URL, keep: Int) {
        let fm = FileManager.default
        guard let names = try? fm.contentsOfDirectory(atPath: directory.path) else { return }
        var files: [(url: URL, modifiedMs: Int64)] = []
        for name in names {
            let url = directory.appendingPathComponent(name)
            var isDirectory: ObjCBool = false
            guard fm.fileExists(atPath: url.path, isDirectory: &isDirectory),
                  !isDirectory.boolValue
            else { continue }
            files.append((url, modificationMs(of: url)))
        }
        guard files.count > keep else { return }
        files.sort { $0.modifiedMs < $1.modifiedMs }
        for file in files.prefix(files.count - keep) {
            try? fm.removeItem(at: file.url)
        }
    }

    // MARK: - Shared plumbing

    /// Protocol-v1 canonical string the verdict HMAC is computed over.
    /// Frozen with `pulse_hook.py canonical_verdict_message` — do not reorder
    /// or reformat.
    private static func canonicalMessage(
        requestID: String,
        digest: String,
        agent: String,
        host: String,
        allow: Bool,
        decidedAtMs: Int64,
        expiresAtMs: Int64
    ) -> Data {
        Data((
            "v1\n" + requestID + "\n" + digest + "\n" + agent + "\n" + host + "\n"
                + (allow ? "allow" : "deny") + "\n"
                + String(decidedAtMs) + "\n" + String(expiresAtMs)
        ).utf8)
    }

    /// Temp-then-rename in the destination's own directory: the hook polling
    /// the spool must never pick up a half-written file, and rename(2) is
    /// atomic only within one filesystem. 0600 is set at
    /// creation, not after — there is no window where another local user
    /// could read the content.
    private static func atomicWrite0600(_ data: Data, to destination: URL) -> Bool {
        let fm = FileManager.default
        let temp = destination.deletingLastPathComponent()
            .appendingPathComponent(".tmp-\(UUID().uuidString)")
        guard fm.createFile(
            atPath: temp.path, contents: data,
            attributes: [.posixPermissions: 0o600]
        ) else { return false }
        guard rename(temp.path, destination.path) == 0 else {
            try? fm.removeItem(at: temp)
            return false
        }
        return true
    }

    /// Hex → bytes, case-insensitive; nil for odd length or a non-hex digit.
    private static func hexBytes(_ hex: String) -> Data? {
        let cleaned = Array(hex.trimmingCharacters(in: .whitespacesAndNewlines).lowercased())
        guard !cleaned.isEmpty, cleaned.count % 2 == 0 else { return nil }
        var data = Data(capacity: cleaned.count / 2)
        var index = 0
        while index < cleaned.count {
            guard let high = nibble(cleaned[index]), let low = nibble(cleaned[index + 1])
            else { return nil }
            data.append(high << 4 | low)
            index += 2
        }
        return data
    }

    private static func nibble(_ character: Character) -> UInt8? {
        guard let ascii = character.asciiValue else { return nil }
        switch ascii {
        case 0x30...0x39: return ascii - 0x30 // 0-9
        case 0x61...0x66: return ascii - 0x57 // a-f
        default: return nil
        }
    }

    /// Untrusted text → file name component. Only `[A-Za-z0-9._-]` survives,
    /// everything else becomes `_`, length is capped, and a component that is
    /// nothing but dots (`.`, `..`) is replaced outright — those are the two
    /// spellings that would climb out of the spool.
    package static func sanitizeComponent(_ raw: String) -> String {
        let sanitized = String(raw.prefix(120).map { ch -> Character in
            let ok = ch.isASCII
                && (ch.isLetter || ch.isNumber || ch == "." || ch == "_" || ch == "-")
            return ok ? ch : "_"
        })
        if sanitized.isEmpty || sanitized.allSatisfy({ $0 == "." }) { return "_" }
        return sanitized
    }

    /// Refuse oversized files up front instead of reading a prefix: a partial
    /// JSON document never parses, so a prefix read would only spend the
    /// bytes to learn nothing.
    private static func boundedRead(_ url: URL, limit: Int) -> Data? {
        SafeRead.regularFile(atPath: url.path, limit: limit)
    }

    private static func modificationMs(of url: URL) -> Int64 {
        let attributes = try? FileManager.default.attributesOfItem(atPath: url.path)
        let date = attributes?[.modificationDate] as? Date
        return Int64((date?.timeIntervalSince1970 ?? 0) * 1000)
    }

    // MARK: - File schemas (v1)

    /// Written by the hook; read here. Extra JSON keys are ignored,
    /// missing required keys fail the decode and the file is skipped.
    private struct RequestFile: Codable {
        package var v: Int
        package var requestID: String
        package var agent: String
        package var host: String
        package var session: String
        package var cwd: String
        package var toolName: String
        package var raisedAtMs: Int64
        package var expiresAtMs: Int64
        package var payloadB64: String
        package var digest: String
        package var truncated: Bool

        package enum CodingKeys: String, CodingKey {
            case v
            case requestID = "request_id"
            case agent
            case host
            case session
            case cwd
            case toolName = "tool_name"
            case raisedAtMs = "raised_at_ms"
            case expiresAtMs = "expires_at_ms"
            case payloadB64 = "payload_b64"
            case digest
            case truncated
        }
    }

    /// Written here; claimed by the hook.
    private struct VerdictFile: Codable {
        package var v: Int
        package var requestID: String
        package var digest: String
        package var agent: String
        package var host: String
        package var allow: Bool
        package var decidedAtMs: Int64
        package var expiresAtMs: Int64
        package var hmac: String

        package enum CodingKeys: String, CodingKey {
            case v
            case requestID = "request_id"
            case digest
            case agent
            case host
            case allow
            case decidedAtMs = "decided_at_ms"
            case expiresAtMs = "expires_at_ms"
            case hmac
        }
    }
}
